name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write

jobs:
  documentation:
    name: update documentations on gitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v5
      - name: ğŸ Install uv
        uses: astral-sh/setup-uv@v7.1.1
        with:
          python-version: 3.13.7
          activate-environment: true
      - name: ğŸ’¾ Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: ğŸ“¦ Install dependencies
        run: |
          uv pip install -r pyproject.toml --group docs
      - name: ğŸ“ Deploy documentation
        run: uv run mkdocs gh-deploy --force